---
title: "MCA"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(FactoMineR)
library(factoextra)
library(tidyverse)
df <- read.csv("../preprocessing/data/feature_generated.csv", stringsAsFactor = T)
```

# Getting categorical data and finalIq for MCA

```{r}
summary(df)
num_cols <- unlist(lapply(df, is.numeric)); num_cols
df_cat <- df[,!num_cols]
df_cat$finalIq <- df$finalIq
df_cat$country_name <- NULL
df_cat$math <- df$math
df_cat$read <- df$read
df_cat$science <- df$science

for (i in 1:(ncol(df_cat)-4)) {
  plot(df_cat[,i], main=colnames(df_cat)[i],
       ylab = "Count", col="steelblue", las = 2)
}
```

# MCA analysis

```{r}
res.mca0<-MCA(df_cat, quanti.sup=c(12:15), graph=FALSE)
names(res.mca0)
print(res.mca0)
summary(res.mca0)

# Eigen values
res.mca0$eig      # Keep dimensions with eigen values bigger than 1/12
length(res.mca0$eig[,1])
fviz_screeplot(res.mca0, addlabels = TRUE, ylim = c(0, 45))
```

## Plots

```{r}
# Individuals
plot(res.mca0,invisible=c("var","quali.sup"),cex=0.7)   # Takes a long time
res.mca0$ind$coord  # Coordinates of the individuals on the factor map

# Variables
plot(res.mca0,invisible=c("ind","quali.sup"), cex=0.5)
res.mca0$var$coord  # Coordinates of the variables
fviz_mca_var(res.mca0, choice = "mca.cor", 
            repel = TRUE, # Avoid text overlapping (slow)
            ggtheme = theme_minimal())
# The plot above helps to identify variables that are the most correlated with each dimension.

# Variable categories
fviz_mca_var(res.mca0, 
             repel = TRUE, 
             ggtheme = theme_minimal())

# Contribution of variable categories to the dimensions 1 and 2
fviz_contrib(res.mca0, choice = "var", axes = 1:2, top = 15)
```

## Dimension description

```{r}
res.desc <- dimdesc(res.mca0, axes = c(1:5))
# Description of dimension 1
res.desc[[1]]
# Description of dimension 2
res.desc[[2]]
# Description of dimension 3
res.desc[[3]]
# Description of dimension 4
res.desc[[4]]
# Description of dimension 5
res.desc[[5]]
```

# MFA

```{r}
df_subset <- df %>%
  select(finalIq, read, science, math, mother_educ, father_educ, desk, room, television, computer_n, car, book, wealth, pop2021)

set.seed(42)
res.mfa <- MFA(df_subset %>% sample_n(10000),
               group = c(4, 2, 6, 1, 1),
               type = c("s", "n", "n", "s", "s"),
               name.group = c("iq_pisa", "parents_education", "commodities", "wealth", "country_pop"))
```

